"""
This module defines the state structure for the AI conversation.
It specifies the types and properties of the state managed by LangGraph.
"""
from typing import Any, TypedDict

from langchain_core.messages import BaseMessage

from app.common.enums import Intent


class CRMState(TypedDict):
    """
    Represents the state of a single conversation session with the CRM chatbot.
    
    Attributes:
        messages (list[BaseMessage]): The history of messages in the conversation.
        intent (Intent | None): The detected intent of the user.
        tool_name (str | None): The name of the tool being called, if any.
        tool_args (dict[str, Any]): The arguments for the tool being called.
        tool_result (Any): The result returned from a tool execution.
        response (str | None): The final response generated by the AI.
    """
    messages: list[BaseMessage]

    intent: Intent | None

    tool_name: str | None

    tool_args: dict[str, Any]

    tool_result: Any

    response: str | None